import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import axios from 'axios';
import { ThemeToggle } from '../../../components/ThemeToggle';
import { PersonalizedLessonViewer } from '../components/PersonalizedLessonViewer';
import { API_BASE_URL } from '../../../config/api';

export const PersonalizedPathWorkspace: React.FC = () => {
    const { pathId } = useParams<{ pathId: string }>();
    const navigate = useNavigate();
    const [token, setToken] = useState<string>('');
    const [pathDetail, setPathDetail] = useState<any>(null);
    const [activeLesson, setActiveLesson] = useState<any>(null);
    const [loading, setLoading] = useState<boolean>(true);

    useEffect(() => {
        const storedToken = localStorage.getItem('token');
        if (!storedToken) {
            navigate('/login');
            return;
        }
        setToken(storedToken);

        if (pathId) {
            fetchPathDetail(pathId, storedToken);
        }
    }, [pathId, navigate]);

    const fetchPathDetail = async (id: string, authToken: string, isSilent: boolean = false) => {
        if (!isSilent) setLoading(true);
        try {
            const res = await axios.get(`${API_BASE_URL}/api/learning-path/${id}`, {
                headers: { Authorization: `Bearer ${authToken}` }
            });
            if (res.data.success) {
                console.log("📚 [WORKSPACE LOADED FULL PATH DATA GENERATED BY GEMINI AI]:", res.data.data);
                setPathDetail(res.data.data);
                if (res.data.data.lessons?.length > 0) {
                    // Retain current active lesson or pick first
                    setActiveLesson((prev: any) => {
                        if (!prev) return res.data.data.lessons[0];
                        const found = res.data.data.lessons.find((l: any) => l.id === prev.id);
                        if (!found) return res.data.data.lessons[0];
                        return {
                            ...found,
                            exercise: found.exercise || prev.exercise
                        };
                    });
                }
            }
        } catch (e) {
            console.error('Fetch path detail error:', e);
        } finally {
            if (!isSilent) setLoading(false);
        }
    };

    return (
        <div className="min-h-screen bg-[#F8FAFC] dark:bg-[#07090E] text-slate-900 dark:text-gray-100 font-sans transition-colors duration-200">
            {/* Header Navigation - Clean Minimalist Bar */}
            <header className="border-b border-slate-200 dark:border-white/10 bg-white/90 dark:bg-[#0B0F17]/80 backdrop-blur-2xl sticky top-0 z-50 transition-colors duration-200">
                <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <Link 
                            to="/personalized-path" 
                            className="group flex items-center gap-2 text-xs font-bold text-slate-600 dark:text-gray-400 hover:text-slate-900 dark:hover:text-white transition-all bg-slate-100 dark:bg-white/[0.04] hover:bg-slate-200/80 dark:hover:bg-white/10 border border-slate-200 dark:border-white/10 px-3 py-1.5 rounded-full"
                        >
                            <span className="group-hover:-translate-x-0.5 transition-transform">←</span>
                            <span>AI Tutor</span>
                        </Link>
                        <span className="text-slate-300 dark:text-gray-700">/</span>
                        <span className="text-xs md:text-sm font-bold text-slate-900 dark:text-white tracking-tight line-clamp-1">
                            {pathDetail?.title || 'Không Gian Thực Hành Lộ Trình Thích Ứng'}
                        </span>
                    </div>

                    <div className="flex items-center gap-4">
                        <div className="hidden sm:flex items-center gap-2 px-3.5 py-1 rounded-full bg-blue-50 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-500/30">
                            <span className="w-2 h-2 rounded-full bg-blue-600 dark:bg-cyan-400 animate-pulse" />
                            <span className="text-[11px] font-mono font-bold text-blue-700 dark:text-cyan-300">
                                {typeof pathDetail?.palNetAvgScore === 'number'
                                    ? `Điểm hồ sơ lúc tạo: ${(pathDetail.palNetAvgScore * 100).toFixed(0)}%`
                                    : 'Chưa có điểm hồ sơ'}
                            </span>
                        </div>
                        <ThemeToggle />
                    </div>
                </div>
            </header>

            {/* Main Workspace Layout */}
            <main className="max-w-7xl mx-auto px-6 py-8">
                {loading ? (
                    <div className="text-center py-28 space-y-4">
                        <div className="relative w-12 h-12 mx-auto">
                            <div className="w-12 h-12 rounded-full border-2 border-blue-200 dark:border-cyan-500/20 border-t-blue-600 dark:border-t-cyan-400 animate-spin" />
                        </div>
                        <p className="text-xs font-mono tracking-wider uppercase text-slate-500 dark:text-gray-400">Đang chuẩn bị không gian học tập thích ứng...</p>
                    </div>
                ) : !pathDetail ? (
                    <div className="text-center py-20 p-6 bg-white dark:bg-[#0D121F] border border-slate-200 dark:border-white/10 rounded-2xl max-w-xl mx-auto shadow-sm space-y-4">
                        <p className="text-sm text-slate-700 dark:text-gray-300">Không tìm thấy dữ liệu lộ trình học tập này.</p>
                        <Link to="/personalized-path" className="inline-block px-5 py-2.5 rounded-full bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold tracking-wide transition-all shadow-sm">
                            Tạo Lộ Trình Mới Với AI Tutor
                        </Link>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
                        {/* Sidebar: Lessons List */}
                        <div className="lg:col-span-4 space-y-4">
                            <div className="bg-white dark:bg-[#0B0F19] rounded-2xl border border-slate-200 dark:border-white/10 p-5 shadow-sm space-y-4">
                                <div className="flex items-center justify-between border-b border-slate-100 dark:border-white/10 pb-3">
                                    <div className="flex items-center gap-2">
                                        <span className="text-base">📖</span>
                                        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 dark:text-white">
                                            Cấu Trúc Lộ Trình
                                        </h3>
                                    </div>
                                    <span className="text-[10px] font-mono font-bold bg-slate-100 dark:bg-white/10 px-2 py-0.5 rounded-md text-slate-700 dark:text-gray-300">
                                        {pathDetail.lessons?.length || 0} Bài
                                    </span>
                                </div>

                                <div className="space-y-2">
                                    {pathDetail.lessons?.map((les: any) => {
                                        const isActive = activeLesson?.id === les.id;
                                        return (
                                            <button
                                                key={les.id}
                                                onClick={() => setActiveLesson(les)}
                                                className={`w-full text-left p-3.5 rounded-xl border transition-all duration-200 text-xs flex items-center justify-between group cursor-pointer ${
                                                    isActive
                                                        ? 'border-blue-600 bg-blue-50/80 dark:border-cyan-500 dark:bg-cyan-950/30 text-blue-800 dark:text-white font-bold shadow-sm'
                                                        : 'border-slate-200 dark:border-white/10 bg-slate-50/60 dark:bg-[#0E1422] text-slate-700 dark:text-gray-400 hover:text-slate-900 dark:hover:text-gray-200 hover:border-slate-300 hover:bg-slate-100'
                                                }`}
                                            >
                                                <div className="flex items-center gap-3 line-clamp-1">
                                                    <span className={`w-6 h-6 rounded-md flex items-center justify-center text-[10px] font-mono font-bold shrink-0 transition-all ${
                                                        isActive
                                                            ? 'bg-blue-600 text-white shadow-sm'
                                                            : 'bg-slate-200 dark:bg-white/10 text-slate-700 dark:text-gray-400 group-hover:bg-slate-300'
                                                    }`}>
                                                        {les.orderIndex}
                                                    </span>
                                                    <span className="line-clamp-1 leading-snug">{les.title}</span>
                                                </div>

                                                {les.isCompleted ? (
                                                    <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded-md bg-emerald-50 text-emerald-700 border border-emerald-200 shrink-0 ml-2">
                                                        ✓ Xong
                                                    </span>
                                                ) : (
                                                    <span className="text-slate-400 group-hover:text-slate-600 dark:text-gray-600 transition-colors shrink-0 ml-2">
                                                        ➔
                                                    </span>
                                                )}
                                            </button>
                                        );
                                    })}
                                </div>
                            </div>
                        </div>

                        {/* Right Area: Lesson Viewer */}
                        <div className="lg:col-span-8">
                            {activeLesson ? (
                                <PersonalizedLessonViewer
                                    lesson={activeLesson}
                                    token={token}
                                    onLessonCompleted={() => fetchPathDetail(pathId!, token, true)}
                                />
                            ) : (
                                <div className="p-12 rounded-2xl bg-white dark:bg-[#0B0F19] border border-slate-200 dark:border-white/10 text-center text-slate-500 dark:text-gray-400 shadow-sm">
                                    <p className="text-sm">Vui lòng chọn một bài học ở cột bên trái để bắt đầu học tập.</p>
                                </div>
                            )}
                        </div>
                    </div>
                )}
            </main>
        </div>
    );
};

export default PersonalizedPathWorkspace;
