import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import axios from 'axios';
import { ThemeToggle } from '../components/ThemeToggle';
import { PersonalizedLessonViewer } from '../components/PersonalizedLessonViewer';

export const PersonalizedPathWorkspace: React.FC = () => {
    const { pathId } = useParams<{ pathId: string }>();
    const navigate = useNavigate();
    const [token, setToken] = useState<string>('');
    const [pathDetail, setPathDetail] = useState<any>(null);
    const [activeLesson, setActiveLesson] = useState<any>(null);
    const [loading, setLoading] = useState<boolean>(true);

    useEffect(() => {
        const storedToken = localStorage.getItem('token');
        if (!storedToken) {
            navigate('/login');
            return;
        }
        setToken(storedToken);

        if (pathId) {
            fetchPathDetail(pathId, storedToken);
        }
    }, [pathId, navigate]);

    const fetchPathDetail = async (id: string, authToken: string) => {
        setLoading(true);
        try {
            const res = await axios.get(`http://localhost:3000/api/learning-path/${id}`, {
                headers: { Authorization: `Bearer ${authToken}` }
            });
            if (res.data.success) {
                console.log("📚 [WORKSPACE LOADED FULL PATH DATA GENERATED BY GEMINI AI]:", res.data.data);
                setPathDetail(res.data.data);
                if (res.data.data.lessons?.length > 0) {
                    // Retain current active lesson or pick first
                    setActiveLesson((prev: any) => {
                        if (!prev) return res.data.data.lessons[0];
                        const found = res.data.data.lessons.find((l: any) => l.id === prev.id);
                        return found || res.data.data.lessons[0];
                    });
                }
            }
        } catch (e) {
            console.error('Fetch path detail error:', e);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen bg-[#07090E] text-gray-100 font-sans selection:bg-cyan-500/30 selection:text-cyan-200">
            {/* Header Navigation - Floating Glass Bar */}
            <header className="border-b border-white/10 bg-[#0B0F17]/80 backdrop-blur-2xl sticky top-0 z-50">
                <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <Link 
                            to="/personalized-path" 
                            className="group flex items-center gap-2 text-xs font-bold text-gray-400 hover:text-white transition-all bg-white/[0.04] hover:bg-white/10 border border-white/10 px-3 py-1.5 rounded-full"
                        >
                            <span className="group-hover:-translate-x-0.5 transition-transform">←</span>
                            <span>AI Tutor</span>
                        </Link>
                        <span className="text-gray-700">/</span>
                        <span className="text-xs md:text-sm font-extrabold text-white tracking-tight line-clamp-1 bg-gradient-to-r from-white via-gray-200 to-gray-400 bg-clip-text text-transparent">
                            {pathDetail?.title || 'Không Gian Thực Hành Lộ Trình Thích Ứng'}
                        </span>
                    </div>

                    <div className="flex items-center gap-4">
                        <div className="hidden sm:flex items-center gap-2 px-3.5 py-1 rounded-full bg-gradient-to-r from-blue-950/40 to-indigo-950/40 border border-blue-500/30">
                            <span className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse" />
                            <span className="text-[11px] font-mono font-bold text-cyan-300">
                                PAL-Net Score: {((pathDetail?.palNetAvgScore || 0.85) * 100).toFixed(0)}%
                            </span>
                        </div>
                        <ThemeToggle />
                    </div>
                </div>
            </header>

            {/* Main Workspace Layout */}
            <main className="max-w-7xl mx-auto px-6 py-8">
                {loading ? (
                    <div className="text-center py-28 space-y-4">
                        <div className="relative w-12 h-12 mx-auto">
                            <div className="w-12 h-12 rounded-full border-2 border-cyan-500/20 border-t-cyan-400 animate-spin" />
                            <div className="absolute inset-0 rounded-full blur-sm bg-cyan-500/20" />
                        </div>
                        <p className="text-xs font-mono tracking-wider uppercase text-gray-400">Đang chuẩn bị không gian học tập thích ứng...</p>
                    </div>
                ) : !pathDetail ? (
                    <div className="text-center py-20 p-1 rounded-2xl bg-white/[0.02] border border-white/10 max-w-xl mx-auto">
                        <div className="p-8 bg-[#0D121F] rounded-xl space-y-4">
                            <p className="text-sm text-gray-300">Không tìm thấy dữ liệu lộ trình học tập này.</p>
                            <Link to="/personalized-path" className="inline-block px-5 py-2.5 rounded-full bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold tracking-wide transition-all shadow-lg">
                                Tạo Lộ Trình Mới Với AI Tutor
                            </Link>
                        </div>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
                        {/* Sidebar: Lessons List - Double Bezel Architecture */}
                        <div className="lg:col-span-4 space-y-4">
                            <div className="p-1 rounded-2xl bg-white/[0.03] border border-white/10 shadow-2xl backdrop-blur-xl">
                                <div className="bg-[#0B0F19] rounded-[calc(1rem-2px)] p-5 space-y-4 border border-white/5">
                                    <div className="flex items-center justify-between border-b border-white/10 pb-3">
                                        <div className="flex items-center gap-2">
                                            <span className="text-base">📖</span>
                                            <h3 className="text-xs font-black uppercase tracking-widest text-white">
                                                Cấu Trúc Lộ Trình
                                            </h3>
                                        </div>
                                        <span className="text-[10px] font-mono font-bold bg-white/10 px-2 py-0.5 rounded-md text-gray-300">
                                            {pathDetail.lessons?.length || 0} Bài
                                        </span>
                                    </div>

                                    <div className="space-y-2">
                                        {pathDetail.lessons?.map((les: any) => {
                                            const isActive = activeLesson?.id === les.id;
                                            return (
                                                <button
                                                    key={les.id}
                                                    onClick={() => setActiveLesson(les)}
                                                    className={`w-full text-left p-3.5 rounded-xl border transition-all duration-300 text-xs flex items-center justify-between group ${
                                                        isActive
                                                            ? 'border-cyan-500 bg-cyan-950/30 text-white font-bold shadow-lg shadow-cyan-500/10'
                                                            : 'border-white/10 bg-[#0E1422] text-gray-400 hover:text-gray-200 hover:border-white/30 hover:bg-white/[0.04]'
                                                    }`}
                                                >
                                                    <div className="flex items-center gap-3 line-clamp-1">
                                                        <span className={`w-6 h-6 rounded-lg flex items-center justify-center text-[10px] font-mono font-bold shrink-0 transition-all ${
                                                            isActive
                                                                ? 'bg-cyan-500 text-black shadow-md'
                                                                : 'bg-white/10 text-gray-400 group-hover:text-white'
                                                        }`}>
                                                            {les.orderIndex}
                                                        </span>
                                                        <span className="line-clamp-1 leading-snug">{les.title}</span>
                                                    </div>

                                                    {les.isCompleted ? (
                                                        <span className="text-[10px] font-black uppercase px-2 py-0.5 rounded-md bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 shrink-0 ml-2">
                                                            ✓ Done
                                                        </span>
                                                    ) : (
                                                        <span className="text-gray-600 group-hover:text-gray-400 transition-colors shrink-0 ml-2">
                                                            ➔
                                                        </span>
                                                    )}
                                                </button>
                                            );
                                        })}
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Right Area: High-End Lesson Viewer */}
                        <div className="lg:col-span-8">
                            {activeLesson ? (
                                <PersonalizedLessonViewer
                                    lesson={activeLesson}
                                    token={token}
                                    onLessonCompleted={() => fetchPathDetail(pathId!, token)}
                                />
                            ) : (
                                <div className="p-12 rounded-2xl bg-[#0B0F19] border border-white/10 text-center text-gray-400">
                                    <p className="text-sm">Vui lòng chọn một bài học ở cột bên trái để bắt đầu học tập.</p>
                                </div>
                            )}
                        </div>
                    </div>
                )}
            </main>
        </div>
    );
};

export default PersonalizedPathWorkspace;
