import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import axios from 'axios';
import { ThemeToggle } from '../components/ThemeToggle';
import { PersonalizedLessonViewer } from '../components/PersonalizedLessonViewer';

export const PersonalizedPathWorkspace: React.FC = () => {
    const { pathId } = useParams<{ pathId: string }>();
    const navigate = useNavigate();
    const [token, setToken] = useState<string>('');
    const [pathDetail, setPathDetail] = useState<any>(null);
    const [activeLesson, setActiveLesson] = useState<any>(null);
    const [loading, setLoading] = useState<boolean>(true);

    useEffect(() => {
        const storedToken = localStorage.getItem('token');
        if (!storedToken) {
            navigate('/login');
            return;
        }
        setToken(storedToken);

        if (pathId) {
            fetchPathDetail(pathId, storedToken);
        }
    }, [pathId, navigate]);

    const fetchPathDetail = async (id: string, authToken: string) => {
        setLoading(true);
        try {
            const res = await axios.get(`http://localhost:3000/api/learning-path/${id}`, {
                headers: { Authorization: `Bearer ${authToken}` }
            });
            if (res.data.success) {
                console.log("📚 [WORKSPACE LOADED FULL PATH DATA GENERATED BY GEMINI AI]:", res.data.data);
                console.log("📝 [LESSONS LIST & EXERCISES]:", res.data.data.lessons);
                setPathDetail(res.data.data);
                if (res.data.data.lessons?.length > 0) {
                    setActiveLesson(res.data.data.lessons[0]);
                }
            }
        } catch (e) {
            console.error('Fetch path detail error:', e);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="min-h-screen bg-[#0D1117] text-gray-100 font-sans">
            {/* Header Navigation */}
            <header className="border-b border-[#30363D] bg-[#161B22] sticky top-0 z-50">
                <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <Link to="/personalized-path" className="text-gray-400 hover:text-white no-underline text-xs font-bold flex items-center gap-1">
                            ⬅ Quay Lại AI Tutor
                        </Link>
                        <span className="text-gray-600">|</span>
                        <span className="text-sm font-bold text-white tracking-tight line-clamp-1">
                            {pathDetail?.title || 'Không gian Thực hành Lộ trình'}
                        </span>
                    </div>

                    <div className="flex items-center gap-4">
                        <span className="text-xs font-bold bg-[#1F6FE5]/20 text-[#58A6FF] px-2.5 py-1 rounded border border-[#1F6FE5]/40">
                            PAL-Net Score: {((pathDetail?.palNetAvgScore || 0.78) * 100).toFixed(0)}%
                        </span>
                        <ThemeToggle />
                    </div>
                </div>
            </header>

            {/* Main Content */}
            <main className="max-w-7xl mx-auto px-6 py-8">
                {loading ? (
                    <div className="text-center py-20">
                        <span className="w-8 h-8 rounded-full border-2 border-[#58A6FF] border-t-transparent animate-spin inline-block mb-4" />
                        <p className="text-sm text-gray-400">Đang tải không gian học tập cá nhân hóa...</p>
                    </div>
                ) : !pathDetail ? (
                    <div className="text-center py-20 bg-[#161B22] border border-[#30363D] rounded-2xl">
                        <p className="text-sm text-gray-400 mb-4">Không tìm thấy dữ liệu lộ trình học tập này.</p>
                        <Link to="/personalized-path" className="bg-[#1F6FE5] text-white text-xs px-4 py-2 rounded-lg font-bold">
                            Tạo Lộ Trình Mới Với AI Tutor
                        </Link>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
                        {/* Sidebar: Lessons List */}
                        <div className="lg:col-span-4 space-y-4">
                            <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-5 shadow-lg space-y-3">
                                <h3 className="text-sm font-bold text-white border-b border-[#30363D] pb-3 flex items-center justify-between">
                                    <span>📖 Danh Sách Bài Học ({pathDetail.lessons?.length || 0})</span>
                                </h3>

                                <div className="space-y-2">
                                    {pathDetail.lessons?.map((les: any) => (
                                        <button
                                            key={les.id}
                                            onClick={() => setActiveLesson(les)}
                                            className={`w-full text-left p-3.5 rounded-xl border transition-all text-xs flex items-center justify-between ${
                                                activeLesson?.id === les.id
                                                    ? 'border-[#3FB950] bg-[#238636]/10 text-white font-bold shadow-md'
                                                    : 'border-[#30363D] bg-[#0D1117] text-gray-300 hover:border-gray-500'
                                            }`}
                                        >
                                            <div className="flex items-center gap-2.5 line-clamp-1">
                                                <span className="w-5 h-5 rounded-full bg-[#21262D] flex items-center justify-center text-[10px] text-gray-400 font-mono">
                                                    {les.orderIndex}
                                                </span>
                                                <span>{les.title}</span>
                                            </div>
                                            {les.isCompleted && (
                                                <span className="text-emerald-400 font-bold text-xs">✓ Done</span>
                                            )}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        </div>

                        {/* Right Area: 3-in-1 Lesson Viewer */}
                        <div className="lg:col-span-8">
                            {activeLesson ? (
                                <PersonalizedLessonViewer
                                    lesson={activeLesson}
                                    token={token}
                                    onLessonCompleted={() => fetchPathDetail(pathId!, token)}
                                />
                            ) : (
                                <div className="bg-[#161B22] border border-[#30363D] rounded-xl p-12 text-center text-gray-400">
                                    <p className="text-sm">Vui lòng chọn một bài học ở cột bên trái để bắt đầu học tập.</p>
                                </div>
                            )}
                        </div>
                    </div>
                )}
            </main>
        </div>
    );
};

export default PersonalizedPathWorkspace;
